#pragma once
#include "isr.h"

#define ESCAPE_PRESSED         0x01
#define ONE_PRESSED            0x02
#define TWO_PRESSED            0x03
#define THREE_PRESSED          0x04
#define FOUR_PRESSED           0x05
#define FIVE_PRESSED           0x06
#define SIX_PRESSED            0x07
#define SEVEN_PRESSED          0x08
#define EIGHT_PRESSED          0x09
#define NINE_PRESSED           0x0A
#define ZERO_PRESSED           0x0B
#define MINUS_PRESSED          0x0C
#define EQUALS_PRESSED         0x0D
#define BACKSPACE_PRESSED      0x0E
#define TAB_PRESSED            0x0F
#define Q_PRESSED              0x10
#define W_PRESSED              0x11
#define E_PRESSED              0x12
#define R_PRESSED              0x13
#define T_PRESSED              0x14
#define Y_PRESSED              0x15
#define U_PRESSED              0x16
#define I_PRESSED              0x17
#define O_PRESSED              0x18
#define P_PRESSED              0x19
#define LEFT_BRACKET_PRESSED   0x1A
#define RIGHT_BRACKET_PRESSED  0x1B
#define ENTER_PRESSED          0x1C
#define LEFT_CTRL_PRESSED      0x1D
#define A_PRESSED              0x1E
#define S_PRESSED              0x1F
#define D_PRESSED              0x20
#define F_PRESSED              0x21
#define G_PRESSED              0x22
#define H_PRESSED              0x23
#define J_PRESSED              0x24
#define K_PRESSED              0x25
#define L_PRESSED              0x26
#define SEMICOLON_PRESSED      0x27
#define SINGLE_QUOTE_PRESSED   0x28
#define BACK_TICK_PRESSED      0x29
#define LEFT_SHIFT_PRESSED     0x2A
#define BACKSLASH_PRESSED      0x2B
#define Z_PRESSED              0x2C
#define X_PRESSED              0x2D
#define C_PRESSED              0x2E
#define V_PRESSED              0x2F
#define B_PRESSED              0x30
#define N_PRESSED              0x31
#define M_PRESSED              0x32
#define COMMA_PRESSED          0x33
#define PERIOD_PRESSED         0x34
#define SLASH_PRESSED          0x35
#define RIGHT_SHIFT_PRESSED    0x36
#define KEYPAD_ASTERISK_PRESSED 0x37
#define LEFT_ALT_PRESSED       0x38
#define SPACE_PRESSED          0x39
#define CAPS_LOCK_PRESSED      0x3A
#define F1_PRESSED             0x3B
#define F2_PRESSED             0x3C
#define F3_PRESSED             0x3D
#define F4_PRESSED             0x3E
#define F5_PRESSED             0x3F
#define F6_PRESSED             0x40
#define F7_PRESSED             0x41
#define F8_PRESSED             0x42
#define F9_PRESSED             0x43
#define F10_PRESSED            0x44
#define NUM_LOCK_PRESSED       0x45
#define SCROLL_LOCK_PRESSED    0x46
#define KEYPAD_7_PRESSED       0x47
#define KEYPAD_8_PRESSED       0x48
#define KEYPAD_9_PRESSED       0x49
#define KEYPAD_MINUS_PRESSED   0x4A
#define KEYPAD_4_PRESSED       0x4B
#define KEYPAD_5_PRESSED       0x4C
#define KEYPAD_6_PRESSED       0x4D
#define KEYPAD_PLUS_PRESSED    0x4E
#define KEYPAD_1_PRESSED       0x4F
#define KEYPAD_2_PRESSED       0x50
#define KEYPAD_3_PRESSED       0x51
#define KEYPAD_0_PRESSED       0x52
#define KEYPAD_PERIOD_PRESSED  0x53
#define F11_PRESSED            0x57
#define F12_PRESSED            0x58
#define ESCAPE_RELEASED         0x81
#define ONE_RELEASED            0x82
#define TWO_RELEASED            0x83
#define THREE_RELEASED          0x84
#define FOUR_RELEASED           0x85
#define FIVE_RELEASED           0x86
#define SIX_RELEASED            0x87
#define SEVEN_RELEASED          0x88
#define EIGHT_RELEASED          0x89
#define NINE_RELEASED           0x8A
#define ZERO_RELEASED           0x8B
#define MINUS_RELEASED          0x8C
#define EQUALS_RELEASED         0x8D
#define BACKSPACE_RELEASED      0x8E
#define TAB_RELEASED            0x8F
#define Q_RELEASED              0x90
#define W_RELEASED              0x91
#define E_RELEASED              0x92
#define R_RELEASED              0x93
#define T_RELEASED              0x94
#define Y_RELEASED              0x95
#define U_RELEASED              0x96
#define I_RELEASED              0x97
#define O_RELEASED              0x98
#define P_RELEASED              0x99
#define LEFT_BRACKET_RELEASED   0x9A
#define RIGHT_BRACKET_RELEASED  0x9B
#define ENTER_RELEASED          0x9C
#define LEFT_CTRL_RELEASED      0x9D
#define A_RELEASED              0x9E
#define S_RELEASED              0x9F
#define D_RELEASED              0xA0
#define F_RELEASED              0xA1
#define G_RELEASED              0xA2
#define H_RELEASED              0xA3
#define J_RELEASED              0xA4
#define K_RELEASED              0xA5
#define L_RELEASED              0xA6
#define SEMICOLON_RELEASED      0xA7
#define SINGLE_QUOTE_RELEASED   0xA8
#define BACK_TICK_RELEASED      0xA9
#define LEFT_SHIFT_RELEASED     0xAA
#define BACKSLASH_RELEASED      0xAB
#define Z_RELEASED              0xAC
#define X_RELEASED              0xAD
#define C_RELEASED              0xAE
#define V_RELEASED              0xAF
#define B_RELEASED              0xB0
#define N_RELEASED              0xB1
#define M_RELEASED              0xB2
#define COMMA_RELEASED          0xB3
#define PERIOD_RELEASED         0xB4
#define SLASH_RELEASED          0xB5
#define RIGHT_SHIFT_RELEASED    0xB6
#define KEYPAD_ASTERISK_RELEASED 0xB7
#define LEFT_ALT_RELEASED       0xB8
#define SPACE_RELEASED          0xB9
#define CAPS_LOCK_RELEASED      0xBA
#define F1_RELEASED             0xBB
#define F2_RELEASED             0xBC
#define F3_RELEASED             0xBD
#define F4_RELEASED             0xBE
#define F5_RELEASED             0xBF
#define F6_RELEASED             0xC0
#define F7_RELEASED             0xC1
#define F8_RELEASED             0xC2
#define F9_RELEASED             0xC3
#define F10_RELEASED            0xC4
#define NUM_LOCK_RELEASED       0xC5
#define SCROLL_LOCK_RELEASED    0xC6
#define KEYPAD_7_RELEASED       0xC7
#define KEYPAD_8_RELEASED       0xC8
#define KEYPAD_9_RELEASED       0xC9
#define KEYPAD_MINUS_RELEASED   0xCA
#define KEYPAD_4_RELEASED       0xCB
#define KEYPAD_5_RELEASED       0xCC
#define KEYPAD_6_RELEASED       0xCD
#define KEYPAD_PLUS_RELEASED    0xCE
#define KEYPAD_1_RELEASED       0xCF
#define KEYPAD_2_RELEASED       0xD0
#define KEYPAD_3_RELEASED       0xD1
#define KEYPAD_0_RELEASED       0xD2
#define KEYPAD_PERIOD_RELEASED  0xD3
#define F11_RELEASED            0xD7
#define F12_RELEASED            0xD8

void keyboard_init();
void keyboard_irq(registers_t* frame);